### ISSUE TITLE
Support for "threshold" configuration

### ISSUE THREAD

**Issue by ra100** [ra100/lc-timer#3]
Allow thresholds with texts to use to be loaded from provided json file, eg:

```js
{
  "thresholds": [{
      threshold: 120,
      action: () => say('Two minutes remaining')
    },
    {
      threshold: 60,
      action: () => say('60 seconds remaining')
    },
    {
      threshold: 1,
      action: () => say('Your suffering is over')
    },
    {
      threshold: 10,
      action: () => say('ten')
    },
    {
      threshold: 5,
      action: () => say('five')
    },
    {
      threshold: 4,
      action: () => say('four')
    },
    {
      threshold: 3,
      action: () => say('three')
    },
    {
      threshold: 2,
      action: () => say('two')
    }
  ]
}
```

**Comment by Snelius30** [comment]
Hey! Do you want to load that file as ur ` const thresholds` variable and file as CLI input like **--thresholds file.json** ?

**Comment by ra100** [comment]
I'd like to have some default thresholds, which can be as const, or it can be in file and use require to import it. And then CLI input, as you wrote  `--thresholds file.json`, that looks good.

**Comment by Snelius30** [comment]
Well, we can't just load this one code as is now. We need to transform that to a plain data (JSON formatted structure), it means remove **action** key as function and leave text only here. Or we need to make truly **thresholds** module with **say** function imported. What do you think?

**Comment by ra100** [comment]
You're right, provided example is not json, I was too lazy to format it. And ooh, I totally missed it, there is function defined :D, idea behind that was to have option to have there some string interpolation. but we can drop it, make it less complex. So have just
```json
{
  "thresholds": [
   { "threshold": 123, "text": "you still have time" }
  ]
}
```
