### ISSUE TITLE
Add option to skip a name

### ISSUE THREAD

**Issue by ra100** [ra100/lc-timer#7]
Idea:
when it's somebody's turn, there should be option to skip them and move to another person in the queue.
Skip by pressing a letter "s".

To be considered, if skipped person should be just skipped as if their turn passed or if they should be set in the queue as the next one.
eg.: order is: `leto, ghani, stil, irul`, when you press skip on `ghani` should the queue be reordered like this? `leto, stil, ghani, irul`?

**Comment by brainfart-be** [comment]
I feel like if you skip someone it should just count as if their turn passed
I would say that if someone want to skip a turn, it would be because that person is busy or not there

If this sound good to you, i can work on it !

**Comment by ra100** [comment]
@brainfart-be that totally make sense, make skip do what you'd expect it to do :)
It's yours. Thanks.

**Comment by brainfart-be** [comment]
@ra100 PR submitted
I had issue with the module ```cli-progress``` and my listener on the stdin stream. 
I hope you will like my solution anyway.
